root: true
extends:
  - eslint:recommended

env:
  browser: true
  commonjs: true
  es6: true
  node: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  sourceType: script
  ecmaVersion: 6

rules: {}
